name: data_standard_dev
channels:
  - conda-forge
dependencies:
  - python=3.13.7
  - numpy=2.3.3
  - pandas=2.3.3
  - h5py=3.14.0
  - pyyaml=6.0.3
  - pip=25.2
  - lume-impact=0.10.2
  - pytest>=7.0
  - pytest-cov>=4.0
  - pip:
    - git+https://github.com/ericcropp/openPMD-beamphysics.git@master
